//Weapons - type (simple, martial, exotic)(0), sm dam(1) (removed), med dam(2), threat(3), critical(4), range(5), type (light, 1-handed, 2-handed, ranged)(6), type 2 (throwable,reach)(7), gp cost (8), weight (9)
oWpn = {
"":["",,"","","",0,"","",0,0],
"Unarmed":["s",,"1d3","20","x2",0,"l","",0,0],
"Bastard sword":["e",,"1d10","19-20","x2",0,"1","",35,6],
"Battleaxe":["m",,"1d8","20","x3",0,"1","",10,6],
"Bolas":["e",,"1d4","20","x2",10,"r","",5,2],
"Club":["s",,"1d6","20","x2",0,"1","",0,3],
"Composite longbow":["m",,"1d8","20","x3",110,"r","",100,3],
"Composite longbow +1":["m",,"1d8","20","x3",110,"r","",200,3],
"Composite longbow +2":["m",,"1d8","20","x3",110,"r","",300,3],
"Composite longbow +3":["m",,"1d8","20","x3",110,"r","",400,3],
"Composite longbow +4":["m",,"1d8","20","x3",110,"r","",500,3],
"Composite longbow +5":["m",,"1d8","20","x3",110,"r","",600,3],
"Composite shortbow":["m",,"1d6","20","x3",70,"r","",75,2],
"Composite shortbow +1":["m",,"1d6","20","x3",70,"r","",150,2],
"Composite shortbow +2":["m",,"1d6","20","x3",70,"r","",225,2],
"Composite shortbow +3":["m",,"1d6","20","x3",70,"r","",300,2],
"Composite shortbow +4":["m",,"1d6","20","x3",70,"r","",375,2],
"Composite shortbow +5":["m",,"1d6","20","x3",70,"r","",450,2],
"Dagger":["s",,"1d4","19-20","x2",10,"l","t",2,1],
"Dart":["s",,"1d4","20","x2",20,"r","t",1,.5],
"Dire flail":["e",,"1d8/1d8","20","x2",0,"2","",90,10],
"Dwarven urgosh":["e",,"1d8/1d6","20","x3",0,"2","",50,12],
"Dwarven waraxe":["e",,"1d10","20","x3",0,"1","",30,8],
"Falchion":["m",,"2d4","18-20","x2",0,"2","",75,8],
"Flail":["m",,"1d8","20","x2",0,"1","",8,5],
"Glaive":["m",,"1d10","20","x3",0,"2","r",8,10],
"Gnome hooked hammer":["e",,"1d8/1d6","20","x3/x4",0,"2","",20,6],
"Greataxe":["m",,"1d12","20","x3",0,"2","",20,12],
"Greatclub":["m",,"1d10","20","x2",0,"2","",5,8],
"Greatsword":["m",,"2d6","19-20","x2",0,"2","",50,8],
"Guisarme":["m",,"2d4","20","x3",0,"2","r",9,12],
"Halberd":["m",,"1d10","20","x3",0,"2","",10,12],
"Hand crossbow":["e",,"1d4","19-20","x2",30,"r","",100,2],
"Handaxe":["m",,"1d6","20","x3",0,"l","",6,3],
"Heavy crossbow":["s",,"1d10","19-20","x2",120,"r","",50,8],
"Heavy flail":["m",,"1d10","19-20","x2",0,"2","",15,10],
"Heavy mace":["s",,"1d8","20","x2",0,"1","",12,8],
"Heavy pick":["m",,"1d6","20","x4",0,"1","",8,6],
"Javelin":["s",,"1d6","20","x2",30,"r","t",1,2],
"Kama":["e",,"1d6","10","x2",0,"l","",2,2],
"Kukri":["m",,"1d4","18-20","x2",0,"l","",8,2],
"Lance":["m",,"1d8","20","x3",0,"2","r",10,10],
"Light crossbow":["s",,"1d8","19-20","x2",80,"r","",35,4],
"Light hammer":["m",,"1d4","20","x2",20,"l","t",1,2],
"Light mace":["s",,"1d6","20","x2",0,"l","",5,4],
"Light pick":["m",,"1d4","20","x4",0,"l","",4,3],
"Longbow":["m",,"1d8","20","x3",100,"r","",75,3],
"Longspear":["s",,"1d8","20","x3",0,"2","r",5,9],
"Longsword":["m",,"1d8","19-20","x2",0,"1","",15,4],
"Morningstar":["s",,"1d8","20","x2",0,"1","",8,6],
"Nunchaku":["e",,"1d6","20","x2",0,"l","",2,2],
"Orc double axe":["e",,"1d8/1d8","20","x3",0,"2","",60,15],
"Punching dagger":["s",,"1d4","20","x3",0,"l","",2,1],
"Quarterstaff":["s",,"1d6/1d6","20","x2",0,"2","",0,4],
"Ranseur":["m",,"2d4","20","x3",0,"2","r",10,12],
"Rapier":["m",,"1d6","18-20","x2",0,"1","",20,2],
"Repeating heavy crossbow":["e",,"1d10","19-20","x2",120,"r","",400,12],
"Repeating light crossbow":["e",,"1d8","19-20","x2",80,"r","",250,6],
"Sai":["e",,"1d4","20","x2",10,"l","",1,1],
"Sap":["m",,"1d6","20","x2",0,"l","",1,2],
"Scimitar":["m",,"1d6","18-20","x2",0,"1","",15,4],
"Scythe":["m",,"2d4","20","x4",0,"2","",18,10],
"Short sword":["m",,"1d6","19-20","x2",0,"l","",10,2],
"Shortbow":["m",,"1d6","20","x3",60,"r","",30,2],
"Shortspear":["s",,"1d6","20","x2",20,"1","t",1,3],
"Shuriken":["e",,"1d2","20","x2",10,"r","t",1,.5],
"Siangham":["e",,"1d6","20","x2",0,"l","",3,1],
"Sickle":["s",,"1d6","20","x2",0,"l","",6,2],
"Sling":["s",,"1d4","20","x2",50,"r","t",0,0],
"Spear":["s",,"1d8","20","x3",20,"2","t",2,6],
"Spiked chain":["e",,"2d4","20","x2",0,"2","r",25,10],
"Spiked gauntlet":["s",,"1d4","20","x2",0,"l","",5,1],
"Throwing axe":["m",,"1d6","20","x2",10,"l","t",8,2],
"Trident":["m",,"1d8","20","x2",10,"1","t",15,4],
"Two-bladed sword":["e",,"1d8/1d8","19-20","x2",0,"2","",100,10],
"Warhammer":["m",,"1d8","20","x3",0,"1","",12,5],
"Whip":["e",,"1d3","20","x2",0,"1","r",1,2]
}
oMnkUnArmd = [,"1d6","1d6","1d6","1d8","1d8","1d8","1d8","1d10","1d10","1d10","1d10","2d6","2d6","2d6","2d6","2d8","2d8","2d8","2d8","2d10"];
oWpnDam = {
  "1d2":{s:"1",m:"1d2",l:"1d3"},
  "1d3":{s:"1d2",m:"1d3",l:"1d4"},
  "1d4":{s:"1d3",m:"1d4",l:"1d6"},
  "1d6":{s:"1d4",m:"1d6",l:"1d8"},
  "1d8":{s:"1d6",m:"1d8",l:"2d6"},
  "1d10":{s:"1d8",m:"1d10",l:"2d8"},
  "1d12":{s:"1d10",m:"1d12",l:"3d6"},
  "2d4":{s:"1d6",m:"2d4",l:"2d6"},
  "2d6":{s:"1d10",m:"2d6",l:"3d6"},
  "2d8":{s:"2d6",m:"2d8",l:"3d8"},
  "2d10":{s:"2d8",m:"2d10",l:"4d8"}
}
//Armor - AC, type, max dex bonus, armor check penalty, arcane spell failure, gp cost
oArmr = {
  "":[0,"",9,0,0,0,0],
  "Padded":[1,"Light",8,0,5,5,10],
  "Leather":[2,"Light",6,0,10,10,15],
  "Studded leather":[3,"Light",5,1,15,25,20],
  "Chain shirt":[4,"Light",4,2,20,100,25],
  "Hide":[3,"Medium",4,3,20,15,25],
  "Scale mail":[4,"Medium",3,4,25,50,30],
  "Breastplate":[5,"Medium",2,5,30,150,40],
  "Splint mail":[6,"Heavy",0,7,40,200,45],
  "Banded mail":[6,"Heavy",1,6,35,250,35],
  "Half-plate":[7,"Heavy",0,7,40,600,50],
  "Full plate":[8,"Heavy",1,6,35,1500,50]
}

//Shields - AC, max dex bonus, armor check penalty, arcane spell failure, gp cost
oShld = {
  "":[0,9,0,0,0,0],
  "Buckler":[1,9,1,5,15,5],
  "Light wooden":[1,9,1,5,3,5],
  "Light steel":[1,9,1,5,9,6],
  "Heavy wooden":[2,9,2,15,7,10],
  "Heavy steel":[2,9,2,15,20,15],
  "Tower shield":[4,2,10,50,30,45]
}

oRc = {
  "":{
    abil:{Str:0,Dex:0,Con:0,Int:0,Wis:0,Cha:0},
    save:{fort:0,rflx:0,will:0,other:""},
    size:"m",lng:[],bLng:[],
    traits:[],bSkill:[],wProf:[],exAsMart:[]},
  "Human":{
    abil:{Str:0,Dex:0,Con:0,Int:0,Wis:0,Cha:0},
    save:{fort:0,rflx:0,will:0,other:""},
    size:"m",lng:["Common"],bLng:[],feats:1,
    traits:[],bSkill:[],wProf:[],exAsMart:[],
    hght:{M:58,F:53,mod:"2d10"},wght:{M:120,F:85,mod:"2d4"},age:{adult:15,mod1:"1d4",mod2:"1d6",mod3:"2d6"}},
  "Dwarf":{
    abil:{Str:0,Dex:0,Con:2,Int:0,Wis:0,Cha:-2},
    save:{fort:0,rflx:0,will:0,other:"+2 vs. poison and spells"},
    size:"m",lng:["Common","Dwarven"],bLng:["Giant","Gnome","Goblin","Orc","Terran","Undercommon"],
    traits:["Darkvision: 60'","+2 Search Stone","+4 vs. bull rush or tripping","+1 atk vs. Orcs and Goblinoids","+4 AC vs. giant type","+2 to appraise stone or metal","+2 to stone or metal craft"],
    bSkill:[],wProf:[],exAsMart:["Dwarven urgosh","Dwarven waraxe"],speed:20,
    hght:{M:45,F:43,mod:"2d4"},wght:{M:130,F:100,mod:"2d6"},age:{adult:40,mod1:"3d6",mod2:"5d6",mod3:"7d6"}},
  "Elf":{
    abil:{Str:0,Dex:2,Con:-2,Int:0,Wis:0,Cha:0},
    save:{fort:0,rflx:0,will:0,other:"Immune to sleep, +2 vs. enchantments"},
    size:"m",lng:["Common","Elven"],bLng:["Draconic","Gnoll","Gnome","Goblin","Orc","Sylvan"],
    traits:["Low-light vision"],bSkill:["Listen+2","Search+2","Spot+2"],wProf:["Longsword","Rapier","Longbow","Composite longbow","Shortbow","Composite shortbow"],exAsMart:[],
    hght:{M:53,F:53,mod:"2d6"},wght:{M:85,F:80,mod:"1d6"},age:{adult:110,mod1:"4d6",mod2:"6d6",mod3:"10d6"}},
  "Gnome":{
    abil:{Str:-2,Dex:0,Con:2,Int:0,Wis:0,Cha:0},
    save:{fort:0,rflx:0,will:0,other:"+2 vs. illusions"},
    size:"s",lng:["Common","Gnome"],bLng:["Draconic","Dwarven","Elven","Giant","Goblin","Orc"],
    traits:["Low-light vision","+4 AC vs. giant type","+2 to Alchemy (craft)","+1 DC for illusions","+1 atk vs. Kobolds and Goblinoids","Speak w/ burrowing mammal 1/day","If Cha > 9: dancing lights, ghost<br />sounds, prestidigitation 1/day"],
    bSkill:["Listen+2","Craft (alchemy)+2"],wProf:[],exAsMart:["Gnome hooked hammer"],speed:20,
    hght:{M:36,F:34,mod:"2d4"},wght:{M:40,F:35,mod:"1d1"},age:{adult:40,mod1:"4d6",mod2:"6d6",mod3:"9d6"}},
  "Halfling":{
    abil:{Str:-2,Dex:2,Con:0,Int:0,Wis:0,Cha:0},
    save:{fort:1,rflx:1,will:1,other:"+2 vs. fear"},
    size:"s",lng:["Common","Halfling"],bLng:["Dwarven","Elven","Gnome","Goblin","Orc"],
    traits:[],bSkill:["Jump+2","Climb+2","Move Silently+2","Listen+2"],wProf:[],exAsMart:[],speed:20,
    hght:{M:32,F:30,mod:"2d4"},wght:{M:30,F:25,mod:"1d1"},age:{adult:20,mod1:"2d4",mod2:"3d6",mod3:"4d6"}},
  "Half-Elf":{
    abil:{Str:0,Dex:0,Con:0,Int:0,Wis:0,Cha:0},
    save:{fort:0,rflx:0,will:0,other:"Immune to sleep, +2 vs. enchantments"},
    size:"m",lng:["Common","Elven"],bLng:[],
    traits:["Low-light vision"],bSkill:["Listen+1","Search+1","Spot+1","Diplomacy+2","Gather Info+2"],wProf:[],exAsMart:[],
    hght:{M:55,F:53,mod:"2d8"},wght:{M:100,F:80,mod:"2d4"},age:{adult:20,mod1:"1d6",mod2:"2d6",mod3:"3d6"}},
  "Half-orc":{
    abil:{Str:2,Dex:0,Con:0,Int:-2,Wis:0,Cha:-2},
    save:{fort:0,rflx:0,will:0,other:""},
    size:"m",lng:["Common","Orc"],bLng:["Draconic","Giant","Gnoll","Goblin","Abyssal"],
    traits:["Darkvision: 60'"],bSkill:[],wProf:[],exAsMart:[],
    hght:{M:58,F:53,mod:"2d12"},wght:{M:150,F:110,mod:"2d6"},age:{adult:20,mod1:"1d4",mod2:"1d6",mod3:"2d6"}},
  "Aasimar":{
    abil:{Str:0,Dex:0,Con:0,Int:0,Wis:2,Cha:2},
    save:{fort:0,rflx:0,will:0,other:""},lvlAdjust:1,
    size:"m",lng:["Common","Celestial"],bLng:["Draconic","Dwarven","Elven","Gnome","Halfling","Sylvan"],
    traits:["Darkvision: 60'","Daylight 1/day","Resistance to acid/cold/electricity 5"],bSkill:["Spot+2","Listen+2"],wProf:[],exAsMart:[]},
  "Aquatic Elf":{
    abil:{Str:0,Dex:2,Con:0,Int:-2,Wis:0,Cha:0},
    save:{fort:0,rflx:0,will:0,other:"Immune to sleep, +2 vs. enchantments"},
    size:"m",lng:["Common","Elven"],bLng:["Draconic","Gnoll","Gnome","Goblin","Orc","Sylvan"],
    traits:["Superior low-light vision","Swim 40'","Gills"],bSkill:["Listen+2","Search+2","Spot+2"],wProf:["Longsword","Rapier","Longbow","Composite longbow","Shortbow","Composite shortbow"],exAsMart:[],
    hght:{M:53,F:53,mod:"2d6"},wght:{M:85,F:80,mod:"1d6"},age:{adult:110,mod1:"4d6",mod2:"6d6",mod3:"10d6"}},
  "Bugbear":{
    abil:{Str:4,Dex:2,Con:2,Int:0,Wis:0,Cha:-2},clsSkls:["Climb","Hide","Listen","Move Silently","Search","Spot"],
    save:{fort:1,rflx:3,will:1,other:""},atk:2,lvl:3,hd:8,feats:2,sklPnt:2,sklPntLvl:6,
    size:"m",lng:["Common","Goblin"],bLng:["Draconic","Elven","Giant","Gnoll","Orc"],
    traits:["Darkvision: 60'","Scent"],bSkill:["Move Silently+4"],wProf:[],exAsMart:[],nAc:3,lvlAdjust:1},
  "Centaur":{
    abil:{Str:8,Dex:4,Con:4,Int:-2,Wis:2,Cha:0},clsSkls:["Listen","Move Silently","Spot","Survival"],
    save:{fort:1,rflx:4,will:4,other:""},atk:4,lvl:4,hd:8,feats:2,sklPnt:2,sklPntLvl:7,speed:50,
    size:"l",lng:["Sylvan","Elven"],bLng:["Common","Gnome","Halfling"],
    traits:["Darkvision: 60'","Space: 10'"],bSkill:["Move Silently+4"],wProf:[],exAsMart:[],nAc:3,lvlAdjust:2},
  "Doppleganger":{
    abil:{Str:2,Dex:2,Con:2,Int:2,Wis:4,Cha:2},clsSkls:["Bluff","Diplomacy","Disguise","Intimidate","Listen","SEnse Motive", "Spot"],
    save:{fort:1,rflx:4,will:4,other:"Immune to sleep and charm"},atk:4,lvl:4,hd:8,feats:2,sklPnt:2,sklPntLvl:7,
    size:"m",lng:["Common"],bLng:["Auran","Dwarven","Eleven","Gnome","Halfling","Giant","Terran"],
    traits:["Darkvision: 60'","Detect thoughts","Change shape"],bSkill:["Bluff+4","Disguise+4"],wProf:[],exAsMart:[],nAc:4,lvlAdjust:4},
  "Deep Dwarf":{
    abil:{Str:0,Dex:0,Con:2,Int:0,Wis:0,Cha:-2},
    save:{fort:0,rflx:0,will:0,other:"+3 vs. poison and spells"},
    size:"m",lng:["Common","Dwarven"],bLng:["Giant","Gnome","Goblin","Orc","Terran","Undercommon"],
    traits:["Darkvision: 90'","Light sensitivity","+2 Search Stone","+4 vs. bull rush or tripping","+1 atk vs. Orcs and Goblinoids","+4 AC vs. giant type","+2 to appraise stone or metal","+2 to stone or metal craft"],
    bSkill:[],wProf:[],exAsMart:["Dwarven urgosh","Dwarven waraxe"],speed:20,
    hght:{M:45,F:43,mod:"2d4"},wght:{M:130,F:100,mod:"2d6"},age:{adult:40,mod1:"3d6",mod2:"5d6",mod3:"7d6"}},
  "Drow":{
    abil:{Str:0,Dex:2,Con:-2,Int:2,Wis:0,Cha:2},
    save:{fort:0,rflx:0,will:0,other:"Immune to sleep, +2 vs. spells"},lvlAdjust:2,
    size:"m",lng:["Common","Elven","Undercommon"],bLng:["Abyssal","Aquan","Draconic","Drow Sign Language","Gnome","Goblin"],
    traits:["Darkvision 120'","Spell resistance 11+lvl","Dancing lights 1/day","Darkness 1/day","Faerie fire 1/day","Light blindness"],bSkill:["Listen+2","Search+2","Spot+2"],wProf:["Hand crossbow","Rapier","Short sword"],exAsMart:[]},
  "Duergar":{
    abil:{Str:0,Dex:0,Con:2,Int:0,Wis:0,Cha:-4},
    save:{fort:0,rflx:0,will:0,other:"+2 vs. spells, Immune to paralysis, phantasms, and poison"},
    size:"m",lng:["Common","Dwarven","Undercommon"],bLng:["Draconic", "Giant", "Goblin", "Orc", "Terran"],
    traits:["Darkvision: 120'","Light sensitivity","+2 Search Stone","+4 vs. bull rush or tripping","+1 atk vs. Orcs and Goblinoids","+4 AC vs. giant type","+2 to appraise stone or metal","+2 to stone or metal craft","Enlarge person 1/day", "Invisibility 1/day"],
    bSkill:["Move Silently+4","Listen+1","Spot+1"],wProf:[],exAsMart:[],speed:20,lvlAdjust:1,
    hght:{M:45,F:43,mod:"2d4"},wght:{M:130,F:100,mod:"2d6"},age:{adult:40,mod1:"3d6",mod2:"5d6",mod3:"7d6"}},
  "Forest Gnome":{
    abil:{Str:-2,Dex:0,Con:2,Int:0,Wis:0,Cha:0},
    save:{fort:0,rflx:0,will:0,other:"+2 vs. illusions"},
    size:"s",lng:["Gnome","Elven","Sylvan","Forest animal"],bLng:["Common","Draconic","Dwarven","Giant","Goblin","Orc"],
    traits:["Pass without trace","Low-light vision","+4 AC vs. giant type","+2 to Alchemy (craft)","+1 DC for illusions","+1 atk vs. Kobolds, Goblinoids,<br />Orcs and Reptilian humanoids","If Cha > 9: dancing lights, ghost<br />sounds, prestidigitation 1/day","Hide (forest) +4"],
    bSkill:["Listen+2","Craft (alchemy)+2","Hide+4"],wProf:[],exAsMart:["Gnome hooked hammer"],speed:20},
  "Goblin":{
    abil:{Str:-2,Dex:2,Con:0,Int:0,Wis:0,Cha:-2},
    save:{fort:0,rflx:0,will:0,other:""},
    size:"s",lng:["Common","Goblin"],bLng:["Draconic","Elven","Giant","Gnoll","Orc"],
    traits:["Darkvision: 60'"],bSkill:["Move Silently+4","Ride+4"],wProf:[],exAsMart:[]},
  "Gnoll":{
    abil:{Str:4,Dex:0,Con:2,Int:-2,Wis:0,Cha:-2},clsSkls:["Listen","Spot"],
    save:{fort:3,rflx:0,will:0,other:""},atk:1,lvl:2,hd:8,feats:1,sklPnt:2,sklPntLvl:5,
    size:"m",lng:["Gnoll"],bLng:["Common","Draconic","Elven","Goblin","Orc"],
    traits:["Darkvision: 60'"],bSkill:[],wProf:[],exAsMart:[],nAc:1,lvlAdjust:1},
  "Grimlock":{
    abil:{Str:4,Dex:2,Con:2,Int:0,Wis:-2,Cha:-4},clsSkls:["Climb","Hide","Listen","Spot"],lvlAdjust:2,
    save:{fort:0,rflx:3,will:3,other:"Immune to gaze attacks, visual effects, illusions"},atk:2,lvl:2,hd:8,feats:1,sklPnt:2,sklPntLvl:5,nAc:4,
    size:"m",lng:["Common","Grimlock"],bLng:["Draconic","Dwarven","Gnome","Terran","Undercommon"],
    traits:["Blindsight: 40'","Hide (mountains or underground) +10","Scent"],bSkill:["Move Silently+4","Ride+4"],wProf:["Battleaxe"],exAsMart:[]},
  "Hobgoblin":{
    abil:{Str:0,Dex:2,Con:2,Int:0,Wis:0,Cha:0},
    save:{fort:0,rflx:0,will:0,other:""},lvlAdjust:1,
    size:"s",lng:["Common","Goblin"],bLng:["Draconic","Dwarven","Infernal","Giant","Orc"],
    traits:["Darkvision: 60'"],bSkill:["Move Silently+4","Ride+4"],wProf:[],exAsMart:[]},
  "Kobold":{
    abil:{Str:-4,Dex:2,Con:-2,Int:0,Wis:0,Cha:0},
    save:{fort:0,rflx:0,will:0,other:""},
    size:"s",lng:["Draconic"],bLng:["Common","Undercommon"],
    traits:["Darkvision: 60'","Light sensitivity"],bSkill:["Craft (trapmaking)+2","Search+2","Profession (miner)"],wProf:[],exAsMart:[],nAc:1},
  "Merfolk":{
    abil:{Str:0,Dex:0,Con:0,Int:0,Wis:0,Cha:0},
    save:{fort:0,rflx:0,will:0,other:""},speed:50,
    size:"m",lng:["Common","Aquan"],bLng:[],
    traits:["Amphibious","Can always take 10 on Swim","Move 5' on land"],bSkill:["Swim+8"],wProf:[],exAsMart:[]},
  "Minotaur":{
    abil:{Str:8,Dex:0,Con:4,Int:-4,Wis:0,Cha:-2},clsSkls:["Intimidate","Jump","Listen","Search","Spot"],
    save:{fort:2,rflx:5,will:5,other:""},atk:6,lvl:6,hd:8,feats:3,sklPnt:2,sklPntLvl:9,
    size:"l",lng:["Common","Giant"],bLng:["Orc","Goblin","Terran"],
    traits:["Darkvision: 60'","Gore (1d8)","Powerful charge","Natural cunning","Scent"],bSkill:["Search+4","Spot+4","Listen+4"],wProf:["Greataxe"],exAsMart:[],nAc:5,lvlAdjust:2},
  "Ogre":{
    abil:{Str:10,Dex:-2,Con:4,Int:-4,Wis:0,Cha:-4},clsSkls:["Climb","Listen","Spot"],
    save:{fort:4,rflx:1,will:1,other:""},atk:3,lvl:4,hd:8,feats:2,sklPnt:2,sklPntLvl:7,
    size:"l",lng:["Common","Giant"],bLng:["Dwarven","Orc","Goblin","Terran"],speed:40,
    traits:["Darkvision: 60'"],bSkill:[],wProf:[],exAsMart:[],nAc:5,lvlAdjust:2},
  "Ogre Mage":{
    abil:{Str:10,Dex:0,Con:6,Int:4,Wis:4,Cha:4},clsSkls:["Concentration","Listen","Spellcraft","Spot"],
    save:{fort:4,rflx:1,will:1,other:""},atk:3,lvl:5,hd:8,feats:2,sklPnt:2,sklPntLvl:8,
    size:"l",lng:["Common","Giant"],bLng:["Dwarven","Goblin","Infernal","Orc"],speed:40,
    traits:["Darkvision: 60'","Fly 40' (good)","Change shape","Regeneration 5","Spell resistance 19","Darkness","Invisibility","Charm person 1/day (DC 14)","Cone of cold 1/day (DC 18)","Gaseous form 1/day","Sleep 1/day (DC 14)"],bSkill:[],wProf:[],exAsMart:[],nAc:5,lvlAdjust:7},
  "Orc":{
    abil:{Str:4,Dex:0,Con:0,Int:-2,Wis:-2,Cha:-2},
    save:{fort:0,rflx:0,will:0,other:""},
    size:"m",lng:["Common","Orc"],bLng:["Dwarven","Giant","Gnoll","Goblin","Undercommon"],
    traits:["Darkvision: 60'","Light sensitivity"],bSkill:[],wProf:[],exAsMart:[]},
  "Svirfneblin":{
    abil:{Str:-2,Dex:2,Con:0,Int:0,Wis:2,Cha:-4},
    save:{fort:2,rflx:2,will:2,other:""},lvlAdjust:3,
    size:"s",lng:["Common","Gnome","Undercommon"],bLng:["Dwarven","Elven","Giant","Goblin","Orc","Terran"],
    traits:["Stonecunning","Spell resistance 11+lvl","Illusion DC +1","Low-light vision","Darkvision 120'","+4 dodge AC","+2 to Alchemy (craft)","+1 DC for illusions","+1 atk vs. Kobolds and Goblinoids","Speak w/ burrowing mammal 1/day","If Cha > 9: blindness/deafness,<br />blur, disguise self 1/day","Nondetection","Hide Underground +2"],
    bSkill:["Listen+2","Craft (alchemy)+2","Hide+2"],wProf:[],exAsMart:["Gnome hooked hammer"],speed:20},
  "Tiefling":{
    abil:{Str:0,Dex:2,Con:0,Int:2,Wis:0,Cha:-2},
    save:{fort:0,rflx:0,will:0,other:""},lvlAdjust:1,
    size:"m",lng:["Common","Infernal"],bLng:["Draconic","Dwarven","Elven","Goblin","Gnome","Halfling","Orc"],
    traits:["Darkvision: 60'","Darkness 1/day","Resistance to fire/cold/electricity 5"],bSkill:["Bluff+2","Hide+2"],wProf:[],exAsMart:[]},
  "Troglodyte":{
    abil:{Str:0,Dex:-2,Con:4,Int:-2,Wis:0,Cha:0},clsSkls:["Hide","Listen"],
    save:{fort:3,rflx:0,will:0,other:""},atk:1,lvl:2,hd:8,feats:1,sklPnt:2,sklPntLvl:5,
    size:"m",lng:["Draconic"],bLng:["Common","Giant","Goblin","Orc"],
    traits:["Darkvision: 90'","Hide (rocky or underground) +4","Multiattack","2 claws (1d4) bite (1d4)","Stench"],bSkill:["Hide+4"],wProf:[],exAsMart:[],nAc:6,lvlAdjust:2},
  "Troll":{
    abil:{Str:12,Dex:4,Con:12,Int:-4,Wis:-2,Cha:-4},clsSkls:["Listen","Spot"],
    save:{fort:5,rflx:2,will:2,other:""},atk:4,lvl:6,hd:8,feats:3,sklPnt:2,sklPntLvl:9,
    size:"l",lng:["Common","Giant"],bLng:["Dwarven","Orc","Goblin","Terran"],speed:40,
    traits:["Darkvision: 60'","Low-light vision","Claw (1d6)","Bite (1d6)","Rend","Regeneration 5","Scent"],bSkill:[],wProf:[],exAsMart:[],nAc:5,lvlAdjust:5}
}

//Languages
var aLang = ["Abyssal","Aquan","Auran","Celestial","Draconic","Dwarven","Elven","Giant","Gnome","Goblin","Gnoll","Halfling","Ignan","Infernal","Orc","Sylvan","Terran","Undercommon"];

//Encumberance
var aMLoad = ["0","4-6","7-13","11-20","14-26","17-33","21-40","24-46","27-53","31-60","34-66","39-76","44-86","51-100","59-116","67-133","77-153","87-173","101-200","117-233","134-266","154-306","174-346","201-400","234-466","267-533","307-613","347-693","401-800","467-933"];
var aHLoad = ["0","7-10","14-20","21-30","27-40","34-50","41-60","47-70","54-80","61-90","67-100","77-115","87-130","101-150","117-175","134-200","154-230","174-260","201-300","234-350","267-400","307-460","347-520","401-600","467-700","534-800","614-920","694-1040","801-1200","934-1400"];

//Class Data HD (0), Fort (1), Reflex (2), Will (3), Class Skills (4), Skill points (5), Weapon prof (6), Armor prof (7), Class features (8), Base attack bonus (9)
oCls = {
  "":[0,"","","",0,0,[],[],[],""],
  "Barbarian":[12,"g","p","p",["Climb","Craft","Handle Animal","Intimidate","Jump","Listen","Ride","Survival","Swim"],4,
    ["Simple","Martial"],["Light","Medium","Shields"],[["Illiteracy","Rage :1/day"],["Uncanny dodge"],["Trap sense +:1"],["Rage :2/day"],["Improved uncanny dodge"],["Trap sense +:2"],["Damage reduction :1/-"],["Rage :3/day"],["Trap sense +:3"],["Damage reduction :2/-"],["Greater rage"],["Rage :4/day", "Trap sense +:4"],["Damage reduction :3/-"],["Indomitable will"],["Trap sense +:5"],["Damage reduction :4/-", "Rage :5/day"],["Tireless rage"],["Trap sense +:6"],["Damage reduction :5/-"],["Mighty rage","Rage :6/day"]],"g"],
  "Bard":[6,"p","g","g",["Appraise","Balance","Bluff","Climb","Concentration","Craft","Decipher Script","Diplomacy","Disguise","Escape Artist","Gather Information","Hide","Jump","Knowledge","Listen","Move Silently","Perform","Profession","Sense Motive","Speak Language","Sleight of Hand","Spellcraft","Swim","Tumble","Use Magic Device"],6,
    ["Simple","Longsword","Rapier","Sap","Short sword","Shortbow","Whip"],["Light","Shields"],[["Bardic knowledge","Bardic music","Countersong","Fascinate","Inspire courage +:1"],[],["Inspire competance"],[],[],["Suggestion"],[],["Inspire courage +:2"],["Inspire greatness"],[],[],["Song of freedom"],[],["Inspire courage +:3"],["Inspire heroics"],[],[],["Mass suggestion"],[],["Inspire courage +:4"]],"a"],
  "Cleric":[8,"g","p","g",["Concentration","Craft","Diplomacy","Heal","Knowledge (arcana)","Knowledge (history)","Knowledge (religion)","Knowledge (the planes)","Profession","Spellcraft"],2,
    ["Simple"],["Light","Medium","Heavy","Shields"],[["Aura","Spontaneous casting","Turn or rebuke undead"]],"a"],
  "Druid":[8,"g","p","g",["Concentration","Craft","Diplomacy","Handle Animal","Heal","Knowledge (nature)","Listen","Profession","Ride","Spellcraft","Spot","Survival","Swim"],4,
    ["Club","Dagger","Dart","Quarterstaff","Scimitar","Sickle","Shortspear","Sling","Spear"],["Padded","Leather","Hide","Shields"],[["Animal companion","Nature Sense","Wild empathy"],["Woodland stride"],["Trackless step"],["Resist nature's lure"],["Wild shape :1/day"],["Wild shape :2/day"],["Wild shape :3/day"],["Wild shape (Large)"],[""],["Wild shape :4/day"],["Wild shape (Tiny)"],["Wild shape (Plant)"],["A thousand faces"],["Wild shape :5/day"],["Timeless body","Wild shape (huge)"],["Wild shape elemental :1/day"],[],["Wild shape :6/day","Wild shape elemental :2/day"],[],["Wild shape elemental :3/day","Wild shape (Huge elemental)"]],"a"],
  "Fighter":[10,"g","p","p",["Climb","Craft","Handle Animal","Intimidate","Jump","Ride","Swim"],2,
    ["Simple","Martial"],["Light","Medium","Heavy","Shields","Tower shield"],[[]],"g"],
  "Monk":[8,"g","g","g",["Balance","Climb","Concentration","Craft","Diplomacy","Escape Artist","Hide","Jump","Knowledge (arcana)","Knowledge (religion)","Listen","Move Silently","Perform","Profession","Sense Motive","Spot","Swim","Tumble"],4,
    ["Unarmed","Club","Light crossbow","Heavy crossbow","Dagger","Handaxe","Javelin","Kama","Nunchaku","Quarterstaff","Sai","Shuriken","Siangham","Sling"],[],
    [["Flurry of Blows :-2/-2","Improved Unarmed Strike","Improved Grapple or Stunning Fist"],["Flurry of Blows :-1/-1","Evasion","Fast movement","Combat Reflexes or Deflect Arrows"],["Flurry of Blows :+0/+0","Still mind"],["Flurry of Blows :+1/+1","Ki strike (magic)","Slow fall :20 ft"],["Flurry of Blows :+2/+2","Purity of body"],["Flurry of Blows :+3/+3","Slow fall :30 ft","Improved Disarm or Improved Trip"],["Flurry of Blows :+4/+4","Wholeness of body"],["Flurry of Blows :+5/+5/+0","Slow fall :40 ft"],["Flurry of Blows :+6/+6/+1","Improved evasion"],["Flurry of Blows :+7/+7/+2","Ki strike (lawful)","Slow fall :50 ft"],["Flurry of Blows :+8/+8/+8/+3","Diamond body","Greater flurry"],["Flurry of Blows :+9/+9/+9/+4","Abundant step","Slow fall :60 ft"],["Flurry of Blows :+9/+9/+9/+4","Diamond soul"],["Flurry of Blows :+10/+10/+10/+5","Slow fall :70 ft"],["Flurry of Blows :+11/+11/+11/+6/+1","Quivering palm"],["Flurry of Blows :+12/+12/+12/+7/+2","Ki strike (adamantine)","Slow fall :80 ft"],["Flurry of Blows :+12/+12/+12/+7/+2","Timless body","Tongue of the sun and moon"],["Flurry of Blows :+13/+13/+13/+8/+3","Slow fall :90 ft"],["Flurry of Blows :+14/+14/+14/+9/+4","Empty body"],["Flurry of Blows :+15/+15/+15/+10/+5","Perfect self","Slow fall :any distance"]],"a"],
  "Paladin":[10,"g","p","p",["Concentration","Craft","Diplomacy","Handle Animal","Heal","Knowledge (nobility and royalty)","Knowledge (religion)","Profession","Ride","Sense Motive"],2,
    ["Simple","Martial"],["Light","Medium","Heavy","Shields"],[["Aura of good","Detect evil","Smite evil :1/day"],["Divine grace","Lay on hands"],["Aura of courage","Divine health"],["Turn undead"],["Smite evil :2/day","Special mount"],["Remove disease :1/week"],[],[],["Remove disease :2/week"],["Smite evil :3/day"],[],["Remove disease :3/week"],[],[],["Remove disease :4/week","Smite evil :4/day"],[],[],["Remove disease :5/week"],[],["Smite evil :5/day"]],"g"],
  "Ranger":[8,"g","g","p",["Climb","Concentration","Craft","Handle Animal","Heal","Hide","Jump","Knowledge (dungeoneering)","Knowledge (geography)","Knowledge (nature)","Listen","Move Silently","Profession","Ride","Search","Spot","Survival","Swim","Use Rope"],6,
    ["Simple","Martial"],["Light","Shields"],[["1st favored enemy","Track","Wild empathy"],["Combat style"],["Endurance"],["Animal companion"],["2nd favored enemy"],["Improved combat style"],["Woodland stride"],["Swift tracker"],["Evasion"],["3rd favored enemy"],["Combat style mastery"],[],["Camoflage"],[],["4th favored enemy"],[],["Hide in plain site"],[],[],["5th favored enemy"]],"g"],
  "Rogue":[6,"p","g","p",["Appraise","Balance","Bluff","Climb","Craft","Decipher Script","Diplomacy","Disable Device","Disguise","Escape Artist","Forgery","Gather Information","Hide","Intimidate","Jump","Knowledge (local)","Listen","Move Silently","Open Lock","Perform","Profession","Search","Sense Motive","Sleight of Hand","Spot","Swim","Tumble","Use Magic Device","Use Rope"],8,
    ["Simple","Hand crossbow","Rapier","Sap","Shortbow","Short sword"],["Light"],[["Sneak attack +:1d6","Trapfinding"],["Evasion"],["Sneak attack +:2d6","Trap sense +:1"],["Uncanny dodge"],["Sneak attack +:3d6"],["Trap sense +:2"],["Sneak attack +:4d6"],["Improved uncanny dodge"],["Sneak attack +:5d6","Trap sense +:3"],["Special ability"],["Sneak attack +:6d6"],["Trap sense +:4"],["Sneak attack +:7d6","Special ability"],[],["Sneak attack +:8d6","Trap sense +:5"],["Special ability"],["Sneak attack +:9d6"],["Trap sense +:6"],["Sneak attack +:10d6","Special ability"]],"a"],
  "Sorcerer":[4,"p","p","g",["Bluff","Concentration","Craft","Knowledge (arcana)","Profession","Spellcraft"],2,
    ["Simple"],[],[["Familiar"]],"p"],
  "Wizard":[4,"p","p","g",["Concentration","Craft","Decipher Script","Knowledge","Profession","Spellcraft"],2,
    ["Club","Dagger","Heavy crossbow","Light crossbow","Quarterstaff"],[],[["Familiar","Scribe scroll"]],"p"],
  "Adept":[6,"p","p","g",["Concentration","Craft","Handle Animal","Knowledge","Profession","Spellcraft","Survival"],2,["Simple"],[],[[],["Familiar"]],"p"],
  "Aristocrat":[8,"p","p","g",["Appraise","Bluff","Diplomacy","Disguise","Forgery","Gather Information","Handle Animal","Intimidate","Knowledge","Listen","Perform","Ride","Sense Motive","Speak Language","Spot","Swim","Survival"],4,
    ["Simple","Martial"],["Light","Medium","Shields"],[[]],"a"],
  "Commoner":[4,"p","p","p",["Climb","Craft","Handle Animal","Jump","Listen","Profession","Ride","Spot","Swim","Use Rope"],2,
    ["Simple"],[],[["Proficient with 1 simple weapon"]],"p"],
  "Expert":[6,"p","p","g",[],6,["Simple"],["Light"],[[]],"a"],
  "Warrior":[8,"g","p","p",["Climb","Handle Animal","Intimidate","Jump","Ride","Swim"],2,["Simple","Martial"],["Light","Medium","Shields"],[[]],"g"]
}

//Trained,Abil,AC penalty multiplier
oSkl = {
"Appraise":["u","Int",0],
"Balance":["u","Dex",1],
"Bluff":["u","Cha",0],
"Climb":["u","Str",1],
"Concentration":["u","Con",0],
"Craft":["u","Int",0],
"Craft (alchemy)":["t","Int",0],
"Craft (armorsmithing)":["t","Int",0],
"Craft (basketweaving)":["t","Int",0],
"Craft (bookbinding)":["t","Int",0],
"Craft (bowmaking)":["t","Int",0],
"Craft (blacksmithing)":["t","Int",0],
"Craft (calligraphy)":["t","Int",0],
"Craft (carpentry)":["t","Int",0],
"Craft (cobbling)":["t","Int",0],
"Craft (gemcutting)":["t","Int",0],
"Craft (leatherworking)":["t","Int",0],
"Craft (locksmithing)":["t","Int",0],
"Craft (painting)":["t","Int",0],
"Craft (pottery)":["t","Int",0],
"Craft (sculpting)":["t","Int",0],
"Craft (shipmaking)":["t","Int",0],
"Craft (stonemasonry)":["t","Int",0],
"Craft (trapmaking)":["t","Int",0],
"Craft (weaponsmithing)":["t","Int",0],
"Craft (weaving)":["t","Int",0],
"Decipher Script":["t","Int",0],
"Diplomacy":["u","Cha",0],
"Disable Device":["t","Int",0],
"Disguise":["u","Cha",0],
"Escape Artist":["u","Dex",1],
"Forgery":["u","Int",0],
"Gather Info":["u","Cha",0],
"Handle Animal":["t","Cha",0],
"Heal":["u","Wis",0],
"Hide":["u","Dex",1],
"Intimidate":["u","Cha",0],
"Jump":["u","Str",1],
"Knowledge (arcana)":["t","Int",0],
"Knowledge (arch and eng)":["t","Int",0],
"Knowledge (dungeoneering)":["t","Int",0],
"Knowledge (geography)":["t","Int",0],
"Knowledge (history)":["t","Int",0],
"Knowledge (local)":["t","Int",0],
"Knowledge (nature)":["t","Int",0],
"Knowledge (nobility)":["t","Int",0],
"Knowledge (religion)":["t","Int",0],
"Knowledge (the planes)":["t","Int",0],
"Listen":["u","Wis",0],
"Move Silently":["u","Dex",1],
"Open Lock":["t","Dex",0],
"Perform":["u","Cha",0],
"Perform (act)":["t","Cha",0],
"Perform (comedy)":["t","Cha",0],
"Perform (dance)":["t","Cha",0],
"Perform (keyboard)":["t","Cha",0],
"Perform (oratory)":["t","Cha",0],
"Perform (percussion)":["t","Cha",0],
"Perform (string instr)":["t","Cha",0],
"Perform (wind instr)":["t","Cha",0],
"Perform (sing)":["t","Cha",0],
"Profession":["t","Wis",0],
"Ride":["u","Dex",0],
"Search":["u","Int",0],
"Sense Motive":["u","Wis",0],
"Sleight of Hand":["t","Dex",1],
"Speak Language":["t","Int",0],
"Spellcraft":["t","Int",0],
"Spot":["u","Wis",0],
"Survival":["u","Wis",0],
"Swim":["u","Str",2],
"Tumble":["t","Dex",1],
"Use Magic Device":["t","Cha",0],
"Use Rope":["u","Dex",0]
}

//Desc (0), Feat Prereq (1), St Prereq (2), Level Prereq (3), Skill Prereq (4) (removed), Skill Bonus (5), Misc Bonus (6), Type (f,w) (7), Selection Type (Weapon, Exotic Weapon, Skill) (8), Stackable (9)
oFts = {
"Acrobatic":["+2 on Jump and Tumble","","","","","Jump+2;Tumble+2","","","",0],
"Agile":["+2 on Balance and Escape Artist","","","","","Balance+2;Escape Artist+2","","","",0],
"Alertness":["+2 on Listen and Spot","","","","","Listen+2;Spot+2","","","",0],
"Animal Affinty":["+2 on Handle Animal and Ride","","","","","Handle Animal+2;Ride+2","","","",0],
"Armor Proficiency (light)":["","","","","","","","","",0],
"Armor Proficiency (medium)":["","","","","","","","","",0],
"Armor Proficiency (heavy)":["","","","","","","","","",0],
"Athletic":["+2 on Climb and Swim","","","","","Climb+2;Swim+2","","","",0],
"Augment Summoning":["Summoned creatures gain +4 Str, +4 Con","Spell Focus (conguration)","","","","","","","",0],
"Blind-Fight":["Reroll miss change for concealment","","","","","","","f","",0],
"Combat Casting":["+4 on Concentration for defensive casting","","","Caster:1","","","","","",0],
"Combat Expertise":["Trade attack bonus for AC","","Int:13","","","","","f","",0],
"Improved Disarm":["+4 on Disarm attempts, no attack of opportunity","Combat Expertise","","","","","","f","",0],
"Improved Feint":["Feint in combat as move action","Combat Expertise","","","","","","f","",0],
"Improved Trip":["+4 on Trip attempts, no attack of opportunity","Combat Expertise","","","","","","f","",0],
"Whirlwind Attack":["One melee attack against each opponent in reach","Combat Expertise;Spring Attack","","","","","","f","",0],
"Combat Reflexes":["Additional attacks of opportunity","","","","","","","f","",0],
"Deceitful":["+2 on Disguise and Forgery","","","","","Disguise+2;Forgery+2","","","",0],
"Deft hands":["+2 on Sleight of Hand and Use Rope","","","","","Sleight of Hand+2;Use Rope+2","","","",0],
"Diligent":["+2 on Appriase and Decipher Script","","","","","Appraise+2;Decipher Script+2","","","",0],
"Dodge":["+1 to AC against selected target","","Dex:13","","","","","f","",0],
"Mobility":["+4 to AC against some attacks of opportunity","","Dex:13","","","","","f","",0],
"Spring Attack":["Move before and after melee attack","Mobility","","Attack:4","","","","f","",0],
"Endurance":["+4 skill and save vs nonleathal damage","","","","","","","","",0],
"Diehard":["Remain conscious at -1 to -9 hp","Endurance","","","","","","","",0],
"Eschew Materials":["Cast spells wihout material components","","","Caster:1","","","","","",0],
"Exotic Weapon Proficiency":["","","","Attack:1","","","","f","e",1],
"Extra Turning":["Can turn 4 more times per day","","","Turning","","","","","",1],
"Great Fortitude":["+2 on Fortitude saves","","","","","","Fort+2","","",0],
"Improved Counterspell":["Counterspell with spell of same school","","","Caster:1","","","","","",0],
"Improved Critical":["Double threat range of weapon","Proficiency","","Attack:8","","","","f","p",1],
"Improved Initiative":["+4 on Initiative","","","","","","Init+4","f","",0],
"Improved Turning":["+1 level on turning checks","","","Turning","","","","","",0],
"Improved Unarmed Strike":["Considered armed even when unarmed","","","","","","","f","",0],
"Improved Grapple":["+4 on grapple checks checks; no attack of opportunity","Improved Unarmed Strike","Dex:13","","","","","f","",0],
"Deflect Arrows":["Deflect one ranged attack per round","Improved Unarmed Strike","Dex:13","","","","","f","",0],
"Snatch Arrows":["Catch a deflected ranged attack","Deflect Arrows","Dex:15","","","","","f","",0],
"Stunning Fist":["Stun opponent with unarmed strike","Improved Unarmed Strike","Dex:13;Wis:13","Attack:8","","","","f","",0],
"Investigator":["+2 on Gather Info and Search","","","","","Gather Info+2;Search+2","","","",0],
"Iron Will":["+2 on Will saves","","","","","","Will+2","","",0],
"Leadership":["Attract cohort and followers","","","Character:6","","","","","",0],
"Lightning Reflexes":["+2 on Reflex saves","","","","","","Reflex+2","","",0],
"Magical Aptitude":["+2 on Spellcraft and Use Magic Device","","","Caster:1","","Spellcraft+2;Use Magic Device+2","","","",0],
"Martial Weapon Proficiency":["","","","","","","","","n",1],
"Mounted Combat":["Negate hits on mount with Ride check","","","Ride:1","","","","f","",0],
"Mounted Archery":["Half penalty for tanged attacks while mounted","Mounted Combat","","","","","","f","",0],
"Ride-by Attack":["Move before and after a mounted charge","Mounted Combat","","","","","","f","",0],
"Spirited Charge":["Double damage with mounted charge","Ride-by Attack","","","","","","f","",0],
"Trample":["Target cannot avoid mounted overrun","Mounted Combat","","","","","","f","",0],
"Natural Spell":["Cast spells while in wild shape","","Wis:13","","","","","","",0],
"Negotiator":["+2 Diplomacy and Sense Motive","","","","","Diplomacy+2;Sense Motive+2","","","",0],
"Nimble Fingers":["+2 Disable Device and Open Lock","","","","","Disable Device+2;Open Lock+2","","","",0],
"Persuasive":["+2 Bluff and Intimidate","","","","","Bluff+2;Intimidate+2","","","",0],
"Point Blank Shot":["+1 ranged attack and damage &lt;= 30'","","","","","","","f","",0],
"Far Shot":["Increase range 1.5X or thrown 2X","Point Blank Shot","","","","","","f","",0],
"Precise Shot":["No -4 penalty for shooting into melee","Point Blank Shot","","","","","","f","",0],
"Improved Precise Shot":["Ignore less than total cover/concealment on ranged attacks","Precise Shot","","Attack:11","","","","f","",0],
"Rapid Shot":["One extra ranged attack each round","Point Blank Shot","","","","","","f","",0],
"Manyshot":["Shoot two or more aows simultaneously","Rapid Shot","","Attack:6","","","","f","",0],
"Shot on the Run":["Move before and after ranged attack","","","Attack:4","","","","f","",0],
"Power Attack":["Trade attack bonus for damage","","Str:13","","","","","f","",0],
"Cleave":["Extra melee attack after dropping target","Power Attack","","","","","","f","",0],
"Great Cleave":["No limit to cleave attacks each round","Cleave","","Attack:4","","","","f","",0],
"Improved Bull Rush":["+4 on bull rush; no attack of opportunity","Power Attack","","","","","","f","",0],
"Improved Overrun":["+4 on overrun; no attack of opportunity","Power Attack","","","","","","f","",0],
"Improved Sunder":["+4 on sunder; no attack of opportunity","Power Attack","","","","","","f","",0],
"Quick Draw":["Draw weapon as free action","","","Attack:1","","","","f","",0],
"Rapid Reload":["Reload crossbow more quickly","Simple Weapon Proficiency","","","","","","f","",0],
"Run":["Run 5X normal speed; +4 Jump with running start","","","","","","","","",0],
"Self-Sufficient":["+2 Heal and Survival","","","","","Heal+2;Survival+2","","","",0],
"Shield Proficiency":["","","","","","","","","",0],
"Improved Shield Bash":["Retain shield AC when bashing","","","","","","","f","",0],
"Tower Shield Proficiency":["","Shield Proficiency","","","","","","","",0],
"Simple Weapon Proficiency":["","","","","","","","","",0],
"Skill Focus":["+3 on selected skill","","","","","Skill+3","","","s",1],
"Spell Focus":["+1 save DC vs specific school of magic","","","Arcane:1","","","","","",1],
"Greater Spell Focus":["+1 save DC vs specific school of magic","Spell Focus","","","","","","","",1],
"Spell Mastery":["Can prepare some spells without spellbook","","","Wizard:1","","","","w","",1],
"Spell Penetration":["+2 on caster level checks to defeat spell resistance","","","Caster:1","","","","","",0],
"Greater Spell Penetration":["+2 on caster level checks to defeat spell resistance","Spell Penetration","","","","","","","",0],
"Stealthy":["+2 Hide and Move Silently","","","","","Hide+2;Move Silently+2","","","",0],
"Toughness":["+3 hp","","","","","","HP+3","","",1],
"Track":["Use survival skill to track","","","","","","","","",0],
"Two-Weapon Fighting":["Reduce 2-weapon fighting penalties","","Dex:15","","","","","f","",0],
"Two-Weapon Defense":["Off-hand weapon give +1 shield bonus to AC","","","","","","","f","",0],
"Improved Two-Weapon Fighting":["Gain second off-hand attack","","","Attack:6","","","","f","",0],
"Greater Two-Weapon Fighting":["Gain third off-hand attack","","","Attack:11","","","","f","",0],
"Weapon Finesse":["Use Dex instead of Str for attack with light weapons","","","Attack:1","","","","f","",0],
"Weapon Focus":["+1 attack with selected weapon","","","Attack:1","","","Attack+1","f","p",1],
"Weapon Specialization":["+2 damage with selected weapon","Weapon Focus","","Fighter:4","","","Dam+2","f","",1],
"Greater Weapon Focus":["+1 attack with selected weapon","Weapon Focus","","Fighter:8","","","Attack+1","f","",1],
"Greater Weapon Specialization":["+2 damage with selected weapon","Weapon Specialization","","Fighter:12","","","Dam+2","f","",1],
"Brew Potion":["Create magic potions","","","Caster:3","","","","w","",0],
"Craft Magic Arms and Armor":["Create magic weapons, armor and shields","","","Caster:5","","","","w","",0],
"Craft Rod":["Create magic rods","","","Caster:9","","","","w","",0],
"Craft Staff":["Create magic staffs","","","Caster:12","","","","w","",0],
"Craft Wand":["Create magic wands","","","Caster:5","","","","w","",0],
"Craft Wondrous Item":["Create magic wondrous items","","","Caster:3","","","","w","",0],
"Forge Ring":["Create magic rings","","","Caster:12","","","","w","",0],
"Scribe Scroll":["Create magic scrolls","","","Caster:1","","","","w","",0],
"Empower Spell":["Increase spell's variable, numeric effects by 50%","","","Caster:1","","","","w","",0],
"Enlarge Spell":["Double spell's range","","","Caster:1","","","","w","",0],
"Extend Spell":["Double spell's duration","","","Caster:1","","","","w","",0],
"Heighten Spell":["Cast spells as higher level","","","Caster:1","","","","w","",0],
"Maximize Spell":["Maximize spell's variable, numeric effects","","","Caster:1","","","","w","",0],
"Quicken Spell":["Cast spells as free action","","","Caster:1","","","","w","",0],
"Silent Spell":["Cast spells without verbal componenets","","","Caster:1","","","","w","",0],
"Still Spell":["Cast spells without somatic componenets","","","Caster:1","","","","w","",0],
"Widen Spell":["Double spell's area","","","Caster:1","","","","w","",0]
}

oGods = {
  "":["","",[],""],
  "Boccob":["Neutral","Neutral",["Knowledge","Magic","Trickery"],"Quarterstaff"],
  "Corellon Larethian":["Chaotic","Good",["Chaos","Good","Protection","War"],"Longsword"],
  "Ehlonna":["Neutral","Good",["Animal","Good","Plant","Sun"],"Longbow"],
  "Erythnul":["Chaotic","Evil",["Chaos","Evil","Trickery","War"],"Morningstar"],
  "Fharlanghn":["Neutral","Neutral",["Luck","Protection","Travel"],"Quarterstaff"],
  "Garl Glittergold":["Neutral","Good",["Good","Protection","Trickery"],"Battleaxe"],
  "Gruumsh":["Chaotic","Evil",["Chaos","Evil","Strength","War"],"Spear"],
  "Heironeous":["Lawful","Good",["Good","Law","War"],"Longsword"],
  "Hextor":["Lawful","Evil",["Destruction","Evil","Law","War"],"Flail"],
  "Kord":["Chaotic","Good",["Chaos","Good","Luck","Strength"],"Greatsword"],
  "Moradin":["Lawful","Good",["Earth","Good","Law","Protection"],"Warhammer"],
  "Nerull":["Neutral","Evil",["Death","Evil","Trickery"],"Scythe"],
  "Obad-Hai":["Neutral","Neutral",["Air","Animal","Earth","Fire","Plant","Water"],"Quarterstaff"],
  "Olidammara":["Chaotic","Neutral",["Chaos","Luck","Trickery"],"Rapier"],
  "Pelor":["Neutral","Good",["Good","Healing","Strength","Sun"],"Mace"],
  "St. Cuthbert":["Lawful","Neutral",["Destruction","Law","Protection","Strength"],"Mace"],
  "Vecna":["Neutral","Evil",["Evil","Knowledge","Magic"],"Dagger"],
  "Wee Jas":["Lawful","Neutral",["Death","Law","Magic"],"Dagger"],
  "Yondalla":["Lawful","Good",["Good","Law","Protection"],"Short sword"]
}
aSchl = ["Aburation","Conjuration","Divination","Enchantment","Evocation","Illusion","Necromancy","Transmutation"];
aSplCrlc = [[],[3,1],[4,2],[4,2,1],[5,3,2],[5,3,2,1],[5,3,3,2],[6,4,3,2,1],[6,4,3,3,2],[6,4,4,3,2,1],[6,4,4,3,3,2],[6,5,4,4,3,2,1],[6,5,4,4,3,3,2],[6,5,5,4,4,3,2,1],[6,5,5,4,4,3,3,2],[6,5,5,5,4,4,3,2,1],[6,5,5,5,4,4,3,3,2],[6,5,5,5,5,4,4,3,2,1],[6,5,5,5,5,4,4,3,3,2],[6,5,5,5,5,5,4,4,3,3],[6,5,5,5,5,5,4,4,4,4]];
aSplWiz = [[],[3,1],[4,2],[4,2,1],[4,3,2],[4,3,2,1],[4,3,3,2],[4,4,3,2,1],[4,4,3,3,2],[4,4,4,3,2,1],[4,4,4,3,3,2],[4,4,4,4,3,2,1],[4,4,4,4,3,3,2],[4,4,4,4,4,3,2,1],[4,4,4,4,4,3,3,2],[4,4,4,4,4,4,3,2,1],[4,4,4,4,4,4,3,3,2],[4,4,4,4,4,4,4,3,2,1],[4,4,4,4,4,4,4,3,3,2],[4,4,4,4,4,4,4,4,3,3],[4,4,4,4,4,4,4,4,4,4]];
aSplSorc = [[],[5,3],[6,4],[6,5],[6,6,3],[6,6,4],[6,6,5,3],[6,6,6,4],[6,6,6,5,3],[6,6,6,6,4],[6,6,6,6,5,3],[6,6,6,6,6,4],[6,6,6,6,6,5,3],[6,6,6,6,6,6,4],[6,6,6,6,6,6,5,3],[6,6,6,6,6,6,6,4],[6,6,6,6,6,6,6,5,3],[6,6,6,6,6,6,6,6,4],[6,6,6,6,6,6,6,6,5,3],[6,6,6,6,6,6,6,6,6,4],[6,6,6,6,6,6,6,6,6,6]];
aSplBard = [[],[2],[3,0],[3,1],[3,2,0],[3,3,1],[3,3,2],[3,3,2,0],[3,3,3,1],[3,3,3,2],[3,3,3,2,0],[3,3,3,3,1],[3,3,3,3,2],[3,3,3,3,2,0],[4,3,3,3,3,1],[4,4,3,3,3,2],[4,4,4,3,3,2,0],[4,4,4,4,3,3,1],[4,4,4,4,4,3,2],[4,4,4,4,4,4,3],[4,4,4,4,4,4,4]];
aSplPalRang = [[],[],[],[],[0,0],[0,0],[0,1],[0,1],[0,1,0],[0,1,0],[0,1,1],[0,1,1,0],[0,1,1,1],[0,1,1,1],[0,2,1,1,0],[0,2,1,1,1],[0,2,2,1,1],[0,2,2,2,1],[0,3,2,2,1],[0,3,3,3,2],[0,3,3,3,3]];
aSplKnwnSorc = [[],[4,2],[5,2],[5,3],[6,3,1],[6,4,2],[7,4,2,1],[7,5,3,2],[8,5,3,2,1],[8,5,4,3,2],[9,5,4,3,2,1],[9,5,5,4,3,2],[9,5,5,4,3,2,1],[9,5,5,4,4,3,2],[9,5,5,4,4,3,2,1],[9,5,5,4,4,4,3,2],[9,5,5,4,4,4,3,2,1],[9,5,5,4,4,4,3,3,2],[9,5,5,4,4,4,3,3,2,1],[9,5,5,4,4,4,3,3,3,2],[9,5,5,4,4,4,3,3,3,3]];
aSplKnwnBard = [[],[4],[5,2],[6,3],[6,3,2],[6,4,3],[6,4,3],[6,4,4,2],[6,4,4,3],[6,4,4,3],[6,4,4,4,2],[6,4,4,4,3],[6,4,4,4,3],[6,4,4,4,4,2],[6,4,4,4,4,3],[6,4,4,4,4,3],[6,5,4,4,4,4,2],[6,5,5,4,4,4,3],[6,5,5,5,4,4,3],[6,5,5,5,5,4,4],[6,5,5,5,5,5,4]];
aSplAdept = [[],[3,1],[3,1],[3,2],[3,2,0],[3,2,1],[3,2,1],[3,3,2],[3,3,2,0],[3,3,2,1],[3,3,2,1],[3,3,3,2],[3,3,3,2,0],[3,3,3,2,1],[3,3,3,2,1],[3,3,3,3,2],[3,3,3,3,2,0],[3,3,3,3,2,1],[3,3,3,3,2,1],[3,3,3,3,3,2],[3,3,3,3,3,2]];
oSpd = {20:15, 30:20, 40:30, 50:35, 60:40, 70:50, 80:55, 90:60, 100:70}